/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Game;

import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        Board board = new Board(600, 600, 3);
        primaryStage.setScene(board.getScene());
        primaryStage.setTitle("Tic Tac Toe");
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }

}
